spring.application.name=GrandLineStonks

spring.datasource.url=jdbc:postgresql://localhost:5432/grand_line_stonks
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
